### ISSUE TITLE
java版本太旧

### ISSUE THREAD

**Issue by Zhaoxian-Wu** [se-2018/se-2018.github.io#15]
我运行我的程序的时候出现这个报错，是因为云桌面自带JAVA版本太旧吗

administrator@vinzor:~/Desktop/calculator$ java caculator
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: caculator has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**Comment by LinJinghua** [comment]
在云平台编译再运行？

**Comment by Zhaoxian-Wu** [comment]
是啊，编译好才运行的

**Comment by Zhaoxian-Wu** [comment]
即使运行BugRunnor也是同样的问题
```shell
administrator@vinzor:~/Desktop/Gridworld/GridWorldCode/projects/firstProject$ lsBugRunner.class  BugRunner.java  gridworld.jar
administrator@vinzor:~/Desktop/Gridworld/GridWorldCode/projects/firstProject$ javac BugRunner.java -classpath ./gridworld.jar 
administrator@vinzor:~/Desktop/Gridworld/GridWorldCode/projects/firstProject$ java BugRunner -cp .:./gridworld.jar:$CLASSPATH
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: info/gridworld/actor/Actor
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: info.gridworld.actor.Actor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by gyakkun** [comment]
java -version的输出是?

**Comment by LinJinghua** [comment]
@MrFive5555 `caculator has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0`见这个[Class compiled by a more recent version of Java Runtime](https://stackoverflow.com/questions/47457105/class-compiled-by-a-more-recent-version-of-java-runtime)

> class file version 53 = Java 9. Your Java 8 JVM cannot execute Java 9 code.

云桌面的Java是Java 8，在云平台编译后再运行怎么可能再报这个错误？
